name : element_data_main_collection
childs :
	data_data_main_collection:
		baseuser_data_main_collection:
			student_data_main_collection:
		nameddata_data_main_collection:
			institute_data_main_collection:
				school_data_main_collection:
				company_data_main_collection:
			filter_data_main_collection: