###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-08-08 11:12:49
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-10-16 17:48:17
###############################################################

name : element_data_main_collection
childs :
	data_data_main_collection:
		baseuser_data_main_collection:
			student_data_main_collection:
			baseusercompany_data_main_collection:
				agent_data_main_collection:
				recruiter_data_main_collection:
		nameddata_data_main_collection:
			institute_data_main_collection:
				school_data_main_collection:
				company_data_main_collection:
			filter_data_main_collection:
			project_data_main_collection:
	skill_data_main_collection:
	link_data_main_collection:
		skilllink_data_main_collection:
